#!usr/bin/env bash

pushd ~/personal/dev/env/.config/nvim
git add .
git commit -m "automated dev commit"
git push
popd

push ~/personal/linux-setup
git add .
git commit -m "automated dev commit"
git push
popd
