#!/usr/bin/env bash


# Download and install nvm:
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash

# in lieu of restarting the shell
\. "$HOME/.nvm/nvm.sh"

# Download and install Node.js:
nvm install 22

# Verify the Node.js version:
node -v # Should print "v22.20.0".

# Download and install pnpm:
corepack enable pnpm

# Verify pnpm version:
pnpm -v

corepack enable yarn

yarn -v

curl -fsSL https://deno.land/install.sh | sh
curl -fsSL https://bun.sh/install | bash


